version: '3'
services:
  "web-application":
    build: "./web-application"
    ports:
      - "3000:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - redis
      - database
      - pgb

  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  
  redis:
    build: ./redis  
    ports: 
      - "6379:6379"
   
  pgb:
    
    container_name: postgres_container
    build: ./postgres
    ports: 
    - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=theRootPassword
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres

    